services:
  - type: web
    name: electroshop-backend
    env: python
    plan: free

    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

      - key: MONGODB_URL
        sync: false

      - key: DATABASE_NAME
        value: electroshop

      - key: COLLECTION_NAME
        value: electroshop

      - key: GROQ_API_KEY
        sync: false
