services:
  - type: web
    name: electroshop-backend
    env: python
    plan: free

    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python main.py

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0

      - key: PORT
        value: 10000

      - key: MONGODB_URL
        value: mongodb+srv://kogamaandres_db_user:fwsAYpZWhHb6Anq1@electroshop.q0k2ovr.mongodb.net/electroshop?retryWrites=true&w=majority

      - key: DATABASE_NAME
        value: electroshop

      - key: COLLECTION_NAME
        value: electroshop

      - key: GROQ_API_KEY
        value: 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
